steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/portfolio']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - portfolio
    - --image
    - gcr.io/$PROJECT_ID/portfolio
    - --region
    - africa-south1
    - --platform
    - managed
    - --allow-unauthenticated
